services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client/
    container_name: mulingu_ude_client
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
    ports:
      - "5173:5173"
    command: "npm run build"

  server:
    build:
      dockerfile: Dockerfile
      context: ./server/
    container_name: mulingu_ude_server
    volumes:
      - ./server:/server
    ports:
      - "3000:3000"
    command: /bin/sh -c "npx prisma generate && npm run build"

volumes:
  node_modules:
