GET http://localhost:3000/api/learn/random?nouns=3&sentences=3&verbs=3

# POST http://localhost:3000/api/mnoun 
# Content-Type: application/json

# {
#   "nouns": [
#     {
#       "language": "en",
#       "singularArticle": "the",
#       "singular": "dog",
#       "pluralArticle": "the",
#       "plural": "dogs"
#     },
#     {
#       "language": "fr",
#       "singularArticle": "le",
#       "singular": "chien",
#       "pluralArticle": "les",
#       "plural": "chiens"
#     },
#     {
#       "language": "de",
#       "singularArticle": "der",
#       "singular": "Hund",
#       "pluralArticle": "die",
#       "plural": "Hunde"
#     }
#   ]
# };




# GET http://localhost:3000/api/learn/mnouns
# Content-Type: application/json

# {
#   "amount": 10
# };




# POST http://localhost:3000/api/auth/signin/github
# Content-Type: application/json

# {
#   "csrfToken": "e3c69de565d11a698405a6697d6f2487b5db917f1376df45d594b7abf0b934b8"
# }

#GET http://localhost:3000/api/auth/providers